[project]
name = "photometa"
version = "1.0.0"
description = "Photo metadata viewer"
requires-python = ">=3.9"
dependencies = [
  "flet==0.28.3",
  "pillow"
]

[tool.flet]
product = "Photo Meta"
org = "com.kaushal.photometa"
company = "Kaushal"

[tool.flet.android]
min_sdk_version = 24

[tool.flet.splash]
color = "#E8EEF6"
dark_color = "#E8EEF6"

[tool.flet.app.boot_screen]
show = false

[tool.flet.app.startup_screen]
show = false